#!/bin/sh -e

CFLAGS=""
CFLAGS="${CFLAGS} -std=c99"
CFLAGS="${CFLAGS} -g"
CFLAGS="${CFLAGS} -Og"
CFLAGS="${CFLAGS} -pedantic"
CFLAGS="${CFLAGS} -pedantic-errors"
CFLAGS="${CFLAGS} -Wall"
CFLAGS="${CFLAGS} -Wextra"
CFLAGS="${CFLAGS} -Werror"
export CFLAGS

cd `dirname $0`
[ ! -f "./configure" ] && autoreconf -fi
exec "./configure" "$@"
